### ISSUE TITLE
Uncaught Error: Class 'App\Listeners\GenerateSitemap' not found

### ISSUE THREAD

**Issue by sambeevors** [tightenco/jigsaw#332]
I tried following the events [example in the docs](https://jigsaw.tighten.co/docs/event-listeners/) but got this error:

```
PHP Fatal error:  Uncaught Error: Class 'App\Listeners\GenerateSitemap' not found in /Users/sambeevors/.composer/vendor/tightenco/jigsaw/src/Events/EventBus.php:33
Stack trace:
#0 /Users/sambeevors/.composer/vendor/illuminate/support/Collection.php(405): TightenCo\Jigsaw\Events\EventBus->TightenCo\Jigsaw\Events\{closure}('App\\Listeners\\G...', 0)
#1 /Users/sambeevors/.composer/vendor/tightenco/jigsaw/src/Events/EventBus.php(35): Illuminate\Support\Collection->each(Object(Closure))
#2 /Users/sambeevors/.composer/vendor/tightenco/jigsaw/src/Jigsaw.php(69): TightenCo\Jigsaw\Events\EventBus->fire('afterBuild', Object(TightenCo\Jigsaw\Jigsaw))
#3 /Users/sambeevors/.composer/vendor/tightenco/jigsaw/src/Jigsaw.php(34): TightenCo\Jigsaw\Jigsaw->fireEvent('afterBuild')
#4 /Users/sambeevors/.composer/vendor/tightenco/jigsaw/src/Console/BuildCommand.php(59): TightenCo\Jigsaw\Jigsaw->build('local', false)
#5 /Users/sambeevors/.composer/vendor/tightenco/jigsaw/src/Console/Command.php(21): TightenCo\Jigsaw\Console\BuildCommand->fire()
#6 / in /Users/sambeevors/.composer/vendor/tightenco/jigsaw/src/Events/EventBus.php on line 33

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5) killed: false, code: 255, signal: null, cmd: 'jigsaw build' }
```
The contents of all the relevant files are the following

> bootstrap.php
```php
<?php

use App\Listeners\GenerateSitemap;

$events->afterBuild(GenerateSitemap::class);
```

> composer.json
```json
{
  "require": {
    "samdark/sitemap": "^2.2",
    "tightenco/jigsaw": "^1.3"
  },
  "autoload": {
    "psr-4": {
      "App\\Listeners\\": "listeners"
    }
  }
}
```

> listeners/GenerateSitemap.php
```php
<?php namespace App\Listeners;

use TightenCo\Jigsaw\Jigsaw;
use samdark\sitemap\Sitemap;

class GenerateSitemap
{
    public function handle(Jigsaw $jigsaw)
    {
        $baseUrl = $jigsaw->getConfig('baseUrl');
        $sitemap = new Sitemap($jigsaw->getDestinationPath() . '/sitemap.xml');

        collect($jigsaw->getOutputPaths())->each(function ($path) use ($baseUrl, $sitemap) {
            if (! $this->isAsset($path)) {
                $sitemap->addItem($baseUrl . $path, time(), Sitemap::DAILY);
            }
        });

        $sitemap->write();
    }

    public function isAsset($path)
    {
        return starts_with($path, '/assets');
    }
}
```

Am I doing something wrong?

**Comment by cossssmin** [comment]
Migh need to run `composer dump-autoload` after having added that class.

**Comment by sambeevors** [comment]
Doesn't seem to sort it unfortunately, oddly enough just tried running it through Netlify and I didn't get that error.

**Comment by sambeevors** [comment]
Did a good old "delete everything and start again" and that seems to have fixed it, not sure what it was in the end, closing because this isn't an issue with Jigsaw itself.

**Comment by SHOCKStudio** [comment]
Hello, I've been thinking for a few good hours about starting a sitemap generator...
I tried according to the documentation (https://jigsaw.tighten.co/docs/event-listeners/) and this thread but it still doesn't work and throws a bug:

 ```
 DONE  Compiled successfully in 441ms                                                                                                                                                                                  3:25:40 PM
       Asset     Size    Chunks             Chunk Names
css/main.css  147 KiB  /js/main  [emitted]  /js/main   
 + 1 hidden assetPHP Fatal error:  Uncaught Error: Class 'App\Listeners\GenerateSitemap' not found in C:\Users\sebas\Dropbox\SHOCKStudio\Projekty\ShockStudio\new page 2019 jilgsaw\newsite\vendor\tightenco\jigsaw\src\Events\EventBus.php:33    Stack trace:
#0 C:\Users\sebas\Dropbox\SHOCKStudio\Projekty\ShockStudio\new page 2019 jilgsaw\newsite\vendor\illuminate\support\Collection.php(475): TightenCo\Jigsaw\Events\EventBus->TightenCo\Jigsaw\Events\{closure}('App\\Listeners\\G...', 0)
#1 C:\Users\sebas\Dropbox\SHOCKStudio\Projekty\ShockStudio\new page 2019 jilgsaw\newsite\vendor\tightenco\jigsaw\src\Events\EventBus.php(35): Illuminate\Support\Collection->each(Object(Closure))#2 C:\Users\sebas\Dropbox\SHOCKStudio\Projekty\ShockStudio\new page 2019 jilgsaw\newsite\vendor\tightenco\jigsaw\src\Jigsaw.php(69): TightenCo\Jigsaw\Events\EventBus->fire('afterBuild', Object(TightenCo\Jigsaw\Jigsaw))       
#3 C:\Users\sebas\Dropbox\SHOCKStudio\Projekty\ShockStudio\new page 2019 jilgsaw\newsite\vendor\tightenco\jigsaw\src\Jigsaw.php(34): TightenCo\Jigsaw\Jigsaw->fire in C:\Users\sebas\Dropbox\SHOCKStudio\Projekty\ShockStudio\new page 2019 jilgsaw\newsite\vendor\tightenco\jigsaw\src\Events\EventBus.php on line 33

[Browsersync] Reloading Browsers...
```

My files:
![Adnotacja 2019-07-16 152720](https://user-images.githubusercontent.com/26645762/61298308-4729a280-a7de-11e9-84ad-5405b13c051c.png)
