### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by cup** [tightenco/jigsaw#401]
I am not seeing any support for tags. Is that the case?

https://gohugo.io/content-management/taxonomies

**Comment by GenieTim** [comment]
You can add your custom metadata in your pages/posts like so as an example (at the top of e.g. portrait.blade.php):
```
---
extends: _layouts.page
title: "Who we are"
short_title: Portrait
tag: page
---
```

An than use [filtering](https://jigsaw.tighten.co/docs/collections-filtering/) (dynamic or static, depending on your usecase) to create a collection for each of your tags.

**Comment by cup** [comment]
@GenieTim thanks for reply, I will try that. Also, do you know any example repos using this method?

**Comment by GenieTim** [comment]
The [Jigsaw Blog Starter Template](http://jigsaw-blog-staging.tighten.co/) (resp. [source](https://github.com/tightenco/jigsaw-blog-template)) uses categories, which might be comparable to your use case.

**Comment by cup** [comment]
@GenieTim I am getting an error:

~~~
$ composer create-project tightenco/jigsaw-blog-template
$ cd jigsaw-blog-template
$ vendor/bin/jigsaw build
Building local site
Loading collections...
Building files from source...
PHP Fatal error: Uncaught Error: Call to undefined function
   Illuminate\View\Compilers\token_get_all() in
   /tmp/jigsaw-blog-template/vendor/illuminate/view/Compilers/
   BladeCompiler.php:204
Stack trace:
#0 /tmp/jigsaw-blog-template/vendor/illuminate/view/Compilers/
   BladeCompiler.php(123): Illuminate\View\Compilers\
   BladeCompiler->compileString('@extends('_layo...')
#1 /tmp/jigsaw-blog-template/vendor/illuminate/view/Engines/
   CompilerEngine.php(51): Illuminate\View\Compilers\
   BladeCompiler->compile('/tmp/jigsaw-blo...')
#2 /tmp/jigsaw-blog-template/vendor/illuminate/view/View.php(142): Illuminate\
   View\Engines\CompilerEngine->get('/tmp/jigsaw-blo...', Array)
#3 /tmp/jigsaw-blog-template/vendor/illuminate/view/View.php(125): Illuminate\
   View\View->getContents()
#4 /tmp/jigsaw-blog-template/vendor/illuminate/view/View.php(90): Illuminate\
   View\View->renderContents()
#5 /tmp/jigsaw-blog-template/vendor/tightenco/jigsaw/src/View/
   ViewRenderer.php(41): Illuminate\View\View->render()
#6 /tmp/jigsaw-blog-template/vendor/tightenco/jigsaw/src/Hand in /tmp/
   jigsaw-blog-template/vendor/illuminate/view/Compilers/BladeCompiler.php on
   line 204
~~~
