### ISSUE TITLE
Call to undefined function ends_with()

### ISSUE THREAD

**Issue by mirorauhala** [tightenco/jigsaw#422]
Created a new project folder and required jigsaw.

After running `./vendor/bin/jigsaw init blog` I get an error regarding ends_with() helper function inside Config.php. 

<details><summary><b>Full terminal output:</b></summary><p>

```terminal
 ~/Code/mirorauhala  ./vendor/bin/jigsaw init blog

> composer require tightenco/jigsaw-blog-template
Using version ^1.0 for tightenco/jigsaw-blog-template
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing samdark/sitemap (2.2.1): Loading from cache
  - Installing tightenco/jigsaw-blog-template (v1.0.12): Loading from cache
Writing lock file
Generating autoload files


> composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Nothing to install or update
Generating autoload files

> npm install

> fsevents@1.2.11 install /Users/mirorauhala/Code/mirorauhala/node_modules/fsevents
> node-gyp rebuild

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/usr/local/Cellar/node/13.7.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mirorauhala/Code/mirorauhala/node_modules/fsevents
gyp ERR! node -v v13.7.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN laravel-mix-purgecss@3.0.0 requires a peer of laravel-mix@^2.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 1232 packages from 881 contributors and audited 21131 packages in 32.135s

29 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


> npm run local

> @ local /Users/mirorauhala/Code/mirorauhala
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --env=local --config=node_modules/laravel-mix/setup/webpack.config.js

98% after emitting SizeLimitsPlugin

 DONE  Compiled successfully in 13236ms                                                                                                                                                         1:40:14 PM

       Asset      Size    Chunks             Chunk Names
 /js/main.js  1.31 MiB  /js/main  [emitted]  /js/main
css/main.css   1.1 MiB  /js/main  [emitted]  /js/main

In config.php line 59:

  Call to undefined function ends_with() (View: /Users/mirorauhala/Code/miror
  auhala/source/_nav/menu.blade.php) (View: /Users/mirorauhala/Code/mirorauha
  la/source/_nav/menu.blade.php) (View: /Users/mirorauhala/Code/mirorauhala/s
  ource/_nav/menu.blade.php)

In config.php line 59:

  Call to undefined function ends_with() (View: /Users/mirorauhala/Code/miror
  auhala/source/_nav/menu.blade.php) (View: /Users/mirorauhala/Code/mirorauha
  la/source/_nav/menu.blade.php)

In config.php line 59:

  Call to undefined function ends_with() (View: /Users/mirorauhala/Code/miror
  auhala/source/_nav/menu.blade.php)

In config.php line 59:

  Call to undefined function ends_with()

build [--pretty PRETTY] [-c|--cache [CACHE]] [--] [<env>]

Your new Jigsaw site was initialized using the 'blog' preset.
```
</p></details>

It seems to be caused by local Config.php file and `tightenco/jigsaw-blog-template` default config.php file.

It may be due to Laravel separating the helper functions to a separate package: https://github.com/laravel/helpers.

**Comment by mirorauhala** [comment]
**Update:**
This gets fixed by adding `laravel/helpers`.
```
$ composer require laravel/helpers
$ ./vendor/bin/jigsaw build
```

**Comment by damiani** [comment]
I've just updated `tightenco/jigsaw-blog-template` to remove the helper and replace it with `Str::endsWith`, if you'd rather go that route. Add `use Illuminate\Support\Str;` to the top of your `config.php` file and replace `ends_with` with `Str::endsWith` and you'll be good to go!
